# -*- coding: utf-8 -*-
"""01 Python desde cero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lVpmdB1nLPYOXOJcwek8B8nD18GtC0Go

**Asignatura:** Programación para Analítica de Datos  
**Serie:** Python desde cero · Cuaderno 1 de 3  
**Modalidad:** trabajo autónomo en Google Colab  
**Duración estimada:** 2 horas a 2 horas y 30 minutos  
**Prerrequisitos:** ninguno

---

**_Propósito_**

Al terminar este cuaderno podrá:

1. reconocer celdas de texto y de código;
2. ejecutar instrucciones en el orden correcto;
3. crear variables con nombres comprensibles;
4. distinguir texto, enteros, decimales y valores lógicos;
5. realizar cálculos respetando el orden de las operaciones;
6. convertir datos de texto a números;
7. comunicar resultados mediante cadenas formateadas;
8. formular comparaciones básicas;
9. localizar y corregir errores frecuentes;
10. verificar cada ejercicio mediante autoevaluación con pistas progresivas.

## Antes de comenzar

1. Abra el archivo en **Google Colab**.
2. Seleccione **Archivo → Guardar una copia en Drive**.
3. Ejecute las celdas en orden con el botón ▶.
4. Edite únicamente las celdas marcadas con `# TODO`.
5. Después de cada ejercicio, ejecute la celda **Autoevaluación**.
6. Si la respuesta no es correcta, recibirá dos pistas y, en el tercer intento, una solución de emergencia.

### Convenciones

- ✅ ejercicio aprobado;
- 🟡 respuesta todavía incorrecta;
- 🧩 pista de apoyo;
- 🛟 solución de emergencia;
- 📊 progreso acumulado.

**Importante:** equivocarse no reduce el puntaje. La meta es comprender la solución.

# 0. Prepare el entorno

Ejecute la siguiente celda una sola vez. Activa la autoevaluación y la exportación final.  
No necesita comprender todavía todo este código.
"""

import csv
import html
import re
from pathlib import Path
from IPython.display import display, HTML

PUNTAJES = {'E1': 8, 'E2': 10, 'E3': 12, 'E4': 10, 'E5': 12, 'E6': 12, 'E7': 10, 'E8': 12, 'E9': 14}

if "RESULTADOS" not in globals():
    RESULTADOS = {}
if "INTENTOS" not in globals():
    INTENTOS = {}
if "nombre_estudiante" not in globals():
    nombre_estudiante = ""

def _tarjeta(mensaje, color_fondo, color_borde):
    display(HTML(
        f'''
        <div style="padding:14px 18px;margin:10px 0;border-radius:10px;
                    background:{color_fondo};border-left:6px solid {color_borde};">
            {mensaje}
        </div>
        '''
    ))

def evaluar(ejercicio, prueba, pistas, solucion):
    '''Ejecuta una prueba y entrega apoyo progresivo sin bloquear el cuaderno.'''
    try:
        aprobado = bool(prueba())
        detalle_error = ""
    except Exception as exc:
        aprobado = False
        detalle_error = f"{type(exc).__name__}: {exc}"

    if aprobado:
        RESULTADOS[ejercicio] = PUNTAJES[ejercicio]
        _tarjeta(
            f"<b>✅ {ejercicio} aprobado.</b> Obtuvo {PUNTAJES[ejercicio]} puntos.",
            "#eaf7ef", "#2e8b57"
        )
        return True

    INTENTOS[ejercicio] = INTENTOS.get(ejercicio, 0) + 1
    intento = INTENTOS[ejercicio]
    RESULTADOS.setdefault(ejercicio, 0)

    mensaje = f"<b>🟡 {ejercicio}: todavía no es correcto.</b><br>"
    if detalle_error:
        mensaje += (
            "<span style='color:#8a3b12;'>Detalle técnico: "
            f"{html.escape(detalle_error)}</span><br>"
        )

    if intento == 1:
        mensaje += f"<b>🧩 Pista 1:</b> {html.escape(pistas[0])}"
    elif intento == 2:
        mensaje += f"<b>🧩 Pista 2:</b> {html.escape(pistas[1])}"
    else:
        mensaje += (
            "<b>🛟 Solución de emergencia:</b><br>"
            "<pre style='background:#fff;padding:10px;border-radius:6px;'>"
            f"{html.escape(solucion)}</pre>"
            "Copie la solución en la celda del ejercicio, ejecútela y vuelva a comprobar."
        )

    _tarjeta(mensaje, "#fff7e6", "#f0a000")
    return False

def mostrar_progreso():
    total = sum(RESULTADOS.get(e, 0) for e in PUNTAJES)
    aprobados = [e for e in PUNTAJES if RESULTADOS.get(e, 0) > 0]
    pendientes = [e for e in PUNTAJES if RESULTADOS.get(e, 0) == 0]
    color = "#2e8b57" if total >= 80 else "#f0a000" if total >= 60 else "#b23a48"

    _tarjeta(
        f"<b>📊 Progreso: {total}/100 puntos</b><br>"
        f"Aprobados: {', '.join(aprobados) if aprobados else 'ninguno'}<br>"
        f"Pendientes: {', '.join(pendientes) if pendientes else 'ninguno'}",
        "#f4f7fb", color
    )

def exportar_autoevaluacion(nombre="estudiante"):
    nombre = nombre.strip()
    if not nombre or nombre == "Escriba aquí su nombre":
        nombre = "estudiante"

    nombre_seguro = re.sub(r"[^A-Za-z0-9_-]+", "_", nombre).strip("_") or "estudiante"
    registros = [
        {
            "estudiante": nombre,
            "ejercicio": e,
            "puntaje_obtenido": RESULTADOS.get(e, 0),
            "puntaje_maximo": maximo,
            "intentos": INTENTOS.get(e, 0),
        }
        for e, maximo in PUNTAJES.items()
    ]

    archivo = Path(f"autoevaluacion_cuaderno1_{nombre_seguro}.csv")
    with archivo.open("w", newline="", encoding="utf-8-sig") as salida:
        escritor = csv.DictWriter(salida, fieldnames=list(registros[0].keys()))
        escritor.writeheader()
        escritor.writerows(registros)

    filas = "".join(
        "<tr>"
        f"<td>{html.escape(str(r['ejercicio']))}</td>"
        f"<td>{r['puntaje_obtenido']}</td>"
        f"<td>{r['puntaje_maximo']}</td>"
        f"<td>{r['intentos']}</td>"
        "</tr>"
        for r in registros
    )
    display(HTML(
        "<table style='border-collapse:collapse;'>"
        "<tr><th style='padding:6px;border:1px solid #ccc;'>Ejercicio</th>"
        "<th style='padding:6px;border:1px solid #ccc;'>Obtenido</th>"
        "<th style='padding:6px;border:1px solid #ccc;'>Máximo</th>"
        "<th style='padding:6px;border:1px solid #ccc;'>Intentos</th></tr>"
        f"{filas}</table>"
    ))
    print(f"Archivo creado: {archivo.name}")

    try:
        from google.colab import files
        files.download(str(archivo))
    except Exception:
        print("Fuera de Colab, el archivo quedó guardado en el directorio actual.")

print("✅ Entorno preparado. Puede comenzar.")
mostrar_progreso()

"""## Identificación

Escriba su nombre. Se utilizará únicamente para nombrar el reporte final.

"""

# TODO: reemplace el texto por su nombre
nombre_estudiante = "Edwin Vargas"
print("Estudiante:", nombre_estudiante)

"""# 1. Cómo se trabaja en un notebook

Un notebook combina:

- **celdas de texto**, para explicar e interpretar;
- **celdas de código**, para ejecutar instrucciones.

Python procesa el código en el orden en que se ejecutan las celdas.

```python
nombre_proyecto = "Control de ventas"
print(nombre_proyecto)
```

- `=` asigna un valor;
- `print()` muestra un resultado;
- `#` inicia un comentario.

"""

# Ejemplo guiado: ejecute sin modificar
nombre_negocio = "Restaurante La Analítica"
numero_sedes = 3
print(nombre_negocio)
print("Número de sedes:", numero_sedes)

"""## Ejercicio E1 — Crear las primeras variables (8 puntos)

Represente:

- `nombre_proyecto = "Control diario de ventas"`;
- `numero_sucursales = 3`;
- `proyecto_activo = True`.

"""

# TODO E1
nombre_proyecto = "Control diario de ventas"
numero_sucursales = 3
proyecto_activo = True

print(nombre_proyecto)
print(numero_sucursales)
print(proyecto_activo)

# Autoevaluación E1
evaluar(
    "E1",
    lambda: (
        nombre_proyecto == "Control diario de ventas"
        and numero_sucursales == 3
        and proyecto_activo is True
    ),
    pistas=[
        "Los textos llevan comillas; los números y True no.",
        "Use exactamente los tres nombres de variable solicitados.",
    ],
    solucion='''nombre_proyecto = "Control diario de ventas"
numero_sucursales = 3
proyecto_activo = True'''
)

"""# 2. Tipos de datos fundamentales

| Tipo | Ejemplo | Uso habitual |
|---|---:|---|
| `str` | `"Centro"` | nombres y categorías |
| `int` | `25` | conteos |
| `float` | `0.15` | porcentajes y promedios |
| `bool` | `True` | condiciones |

`type()` informa el tipo de un valor.

"""

# Ejemplo guiado
sede = "Centro"
pedidos = 18
ticket_promedio = 27500.5
meta_cumplida = False

print(type(sede))
print(type(pedidos))
print(type(ticket_promedio))
print(type(meta_cumplida))

"""## Ejercicio E2 — Reconocer tipos (10 puntos)

Guarde los tipos de las variables de E1 en:

- `tipo_nombre`;
- `tipo_sucursales`;
- `tipo_estado`.

"""

# TODO E2
tipo_nombre = type(nombre_proyecto)
tipo_sucursales = type(numero_sucursales)
tipo_estado = type(proyecto_activo)

print(tipo_nombre)
print(tipo_sucursales)
print(tipo_estado)

# Autoevaluación E2
evaluar(
    "E2",
    lambda: (
        tipo_nombre is str
        and tipo_sucursales is int
        and tipo_estado is bool
    ),
    pistas=[
        "La forma general es tipo_variable = type(variable).",
        "Aplique type() a las tres variables creadas en E1.",
    ],
    solucion='''tipo_nombre = type(nombre_proyecto)
tipo_sucursales = type(numero_sucursales)
tipo_estado = type(proyecto_activo)'''
)

"""# 3. Operaciones aritméticas

Operadores frecuentes: `+`, `-`, `*`, `/`, `**` y `%`.

## Ejercicio E3 — Calcular una venta (12 puntos)

Una venta tiene 4 unidades, precio unitario de `$18.500` y costo unitario de `$11.200`.

Calcule `ingreso_bruto`, `costo_total` y `margen_bruto`.
"""

# TODO E3
cantidad = 4
precio_unitario = 18500
costo_unitario = 11200

ingreso_bruto = 18500*4
costo_total = 11200*4
margen_bruto = ingreso_bruto - costo_total

print("Ingreso bruto:", ingreso_bruto)
print("Costo total:", costo_total)
print("Margen bruto:", margen_bruto)

# Autoevaluación E3
evaluar(
    "E3",
    lambda: (
        ingreso_bruto == 74000
        and costo_total == 44800
        and margen_bruto == 29200
    ),
    pistas=[
        "Multiplique cantidad por cada valor unitario.",
        "El margen es ingreso_bruto - costo_total.",
    ],
    solucion='''ingreso_bruto = cantidad * precio_unitario
costo_total = cantidad * costo_unitario
margen_bruto = ingreso_bruto - costo_total'''
)

"""# 4. Orden de las operaciones y paréntesis

Python respeta la jerarquía matemática. Los paréntesis hacen explícita la intención:

```python
porcentaje = (parte / total) * 100
```

## Ejercicio E4 — Porcentaje de margen (10 puntos)

Calcule `porcentaje_margen = margen_bruto / ingreso_bruto × 100` y redondee a dos decimales con `round()`.
"""

# TODO E4
porcentaje_margen = margen_bruto / ingreso_bruto * 100
porcentaje_margen = round(porcentaje_margen, 2)
print("Porcentaje de margen:", porcentaje_margen)

# Autoevaluación E4
evaluar(
    "E4",
    lambda: porcentaje_margen == 39.46,
    pistas=[
        "Divida margen_bruto entre ingreso_bruto y multiplique por 100.",
        "Use round((margen_bruto / ingreso_bruto) * 100, 2).",
    ],
    solucion='''porcentaje_margen = round(
    (margen_bruto / ingreso_bruto) * 100,
    2
)'''
)

"""# 5. Texto y cadenas formateadas

Las **f-strings** combinan texto y variables:

```python
mensaje = f"{producto} generó ${ingreso:,.0f}"
```

## Ejercicio E5 — Comunicar un KPI (12 puntos)

Cree `mensaje_resultado` que incluya:

- `"Bowl Andino"`;
- el ingreso bruto;
- el porcentaje de margen.
"""

# TODO E5
producto = "Bowl Andino"
mensaje_resultado = f"{producto} generó ${ingreso_bruto:,.0f} margen de {porcentaje_margen:.2f}%."
print(mensaje_resultado)

# Autoevaluación E5
def _comprobar_mensaje_resultado():
    texto = str(mensaje_resultado)
    digitos = "".join(c for c in texto if c.isdigit())
    return "Bowl Andino" in texto and "74000" in digitos and "3946" in digitos

evaluar(
    "E5",
    _comprobar_mensaje_resultado,
    pistas=[
        "Use una f-string con producto, ingreso_bruto y porcentaje_margen.",
        "Incluya el porcentaje con dos decimales: {porcentaje_margen:.2f}%.",
    ],
    solucion='''mensaje_resultado = (
    f"{producto} generó ${ingreso_bruto:,.0f} "
    f"con un margen de {porcentaje_margen:.2f}%."
)'''
)

"""# 6. Conversión de tipos

Los datos pueden llegar como texto:

```python
cantidad = int("4")
precio = float("18500.50")
```

`int()`, `float()` y `str()` convierten valores.

## Ejercicio E6 — Convertir datos recibidos como texto (12 puntos)

Convierta `"4"` a entero y `"18500.50"` a decimal. Después calcule `total_convertido`.
"""

# TODO E6
cantidad_texto = "4"
precio_texto = "18500.50"

cantidad_convertida = int(cantidad_texto)
precio_convertido = float(precio_texto)
total_convertido = cantidad_convertida * precio_convertido

print(cantidad_convertida)
print(precio_convertido)
print(total_convertido)

# Autoevaluación E6
evaluar(
    "E6",
    lambda: (
        cantidad_convertida == 4
        and isinstance(cantidad_convertida, int)
        and precio_convertido == 18500.5
        and isinstance(precio_convertido, float)
        and total_convertido == 74002.0
    ),
    pistas=[
        "Use int(cantidad_texto) y float(precio_texto).",
        "Multiplique las dos variables convertidas.",
    ],
    solucion='''cantidad_convertida = int(cantidad_texto)
precio_convertido = float(precio_texto)
total_convertido = cantidad_convertida * precio_convertido'''
)

"""# 7. Comparaciones

Las comparaciones producen `True` o `False`: `==`, `!=`, `>`, `<`, `>=`, `<=`.

- `=` asigna;
- `==` compara.

## Ejercicio E7 — Verificar una meta (10 puntos)

- `cumple_meta`: total convertido mayor o igual a `$70.000`;
- `es_venta_grande`: cantidad convertida mayor o igual a `5`.
"""

# TODO E7
meta_venta = 70000
cumple_meta = total_convertido >= meta_venta
cantidad_convertida = 4
es_venta_grande = cantidad_convertida >= 5
print("Cumple meta:", cumple_meta)
print("Venta grande:", es_venta_grande)

# Autoevaluación E7
evaluar(
    "E7",
    lambda: cumple_meta is True and es_venta_grande is False,
    pistas=[
        "Use >= para ambas comparaciones.",
        "Compare total_convertido con meta_venta y cantidad_convertida con 5.",
    ],
    solucion='''cumple_meta = total_convertido >= meta_venta
es_venta_grande = cantidad_convertida >= 5'''
)

"""# 8. Aprender a leer errores

Errores frecuentes:

```python
print(precio_unidad)     # NameError
total = "25000" + 2      # TypeError
print("Resultado"        # SyntaxError
```

Estrategia: lea la última línea, ubique la línea señalada, revise nombres, comillas, paréntesis y tipos, corrija una sola cosa y vuelva a ejecutar.

## Ejercicio E8 — Corregir una operación (12 puntos)

Represente una venta de 2 unidades a `$25.000`.

Obtenga `total_corregido = 50000` y un mensaje con `"Total de la venta"` y el número `50000`.
"""

# TODO E8
precio_corregido = 25000
cantidad_corregida = 2
total_corregido = precio_corregido*cantidad_corregida
mensaje_corregido = f"Total de la venta: ${total_corregido:,.0f}"
print(mensaje_corregido)

# Autoevaluación E8
def _comprobar_correccion():
    texto = str(mensaje_corregido)
    digitos = "".join(c for c in texto if c.isdigit())
    return (
        precio_corregido == 25000
        and cantidad_corregida == 2
        and total_corregido == 50000
        and "Total de la venta" in texto
        and "50000" in digitos
    )

evaluar(
    "E8",
    _comprobar_correccion,
    pistas=[
        "Los valores numéricos no llevan comillas.",
        "Multiplique precio por cantidad y construya una f-string.",
    ],
    solucion='''precio_corregido = 25000
cantidad_corregida = 2
total_corregido = precio_corregido * cantidad_corregida
mensaje_corregido = f"Total de la venta: ${total_corregido:,.0f}"'''
)

"""# 9. Desafío integrador: construir un comprobante

Venta:

- 3 bebidas a `$8.000`;
- 2 almuerzos a `$24.000`;
- servicio del `8 %`.

## Ejercicio E9 — Calcular y comunicar el total (14 puntos)

Calcule `subtotal`, `valor_servicio`, `total_pagar` y `comprobante`.

"""

# TODO E9
unidades_bebida = 3
precio_bebida = 8000
unidades_almuerzo = 2
precio_almuerzo = 24000
porcentaje_servicio = 0.08

subtotal = (precio_bebida*unidades_bebida)+(precio_almuerzo*unidades_almuerzo)
valor_servicio = subtotal*porcentaje_servicio
total_pagar = subtotal+valor_servicio
comprobante = (
    f"Subtotal: ${subtotal:,.0f} | "
    f"Servicio: ${valor_servicio:,.0f} | "
    f"Total: ${total_pagar:,.0f}"
)

print(comprobante)

# Autoevaluación E9
def _comprobar_comprobante():
    texto = str(comprobante)
    digitos = "".join(c for c in texto if c.isdigit())
    return (
        subtotal == 72000
        and valor_servicio == 5760
        and total_pagar == 77760
        and "72000" in digitos
        and "5760" in digitos
        and "77760" in digitos
    )

evaluar(
    "E9",
    _comprobar_comprobante,
    pistas=[
        "Sume el total de bebidas y el total de almuerzos.",
        "El servicio es subtotal * porcentaje_servicio; después súmelo.",
    ],
    solucion='''subtotal = (
    unidades_bebida * precio_bebida
    + unidades_almuerzo * precio_almuerzo
)
valor_servicio = subtotal * porcentaje_servicio
total_pagar = subtotal + valor_servicio
comprobante = (
    f"Subtotal: ${subtotal:,.0f} | "
    f"Servicio: ${valor_servicio:,.0f} | "
    f"Total: ${total_pagar:,.0f}"
)'''
)

"""# 10. Interpretación profesional

Responda en una nueva celda de texto:

1. ¿Por qué un número entre comillas no se comporta igual que un número sin comillas?
2. ¿Qué riesgo existe al calcular porcentajes sin paréntesis claros?
3. ¿Qué aporta una frase interpretativa frente a mostrar únicamente `77760`?
4. ¿Qué dato adicional necesitaría la gerencia para evaluar la rentabilidad real?

##Respuestas punto 10:

1. ¿Por qué un número entre comillas no se comporta igual que un número sin comillas?
  Rta: Porque es un valor que se puede operar con otros y lo que va entre comillas son textos.
2. ¿Qué riesgo existe al calcular porcentajes sin paréntesis claros?
  Rta: la prioridad de operaciones podría realizar una operación antes que la otra.
3. ¿Qué aporta una frase interpretativa frente a mostrar únicamente `77760`?
  Rta: Que el usuario pueda entender de que se trata el valor arrojado.
4. ¿Qué dato adicional necesitaría la gerencia para evaluar la rentabilidad real?
  Rta: A la rentabilidad nominal se le debe restar la inflación.

# 11. Resultado final y exportación

- **80 o más:** continúe al Cuaderno 2;
- **60 a 79:** revise los ejercicios pendientes;
- **menos de 60:** repita variables, tipos y operaciones.
"""

mostrar_progreso()

# Exporte el reporte únicamente cuando termine.
exportar_autoevaluacion(nombre_estudiante)

"""# 12. Lista de comprobación

- [ ] guardé una copia en Drive;
- [ ] ejecuté todas las celdas desde el inicio y en orden;
- [ ] obtuve al menos 80/100;
- [ ] respondí la interpretación profesional;
- [ ] generé el CSV final de ejercicios, puntajes e intentos;
- [ ] conservé el enlace del notebook.

# Recursos oficiales

- [Google Colab: preguntas frecuentes](https://research.google.com/colaboratory/intl/es/faq.html)
- [Tutorial oficial de Python: introducción](https://docs.python.org/es/3/tutorial/introduction.html)
- [Tipos numéricos](https://docs.python.org/es/3/library/stdtypes.html#numeric-types-int-float-complex)
- [Cadenas formateadas](https://docs.python.org/es/3/tutorial/inputoutput.html#formatted-string-literals)

> El primer paso para programar no es memorizar sintaxis: es representar datos, ejecutar cálculos y explicar el resultado.

"""