# -*- coding: utf-8 -*-
"""Ejercicios de práctica NumPy y pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikgJs4LACzSkwsQdDzBFTjiM-CSmhvSa

# **Ejercicios de práctica NumPy y pandas**

# **1 Importar la biblioteca**
"""

import numpy as np


print(np.__version__)

"""# **2 Del listado al arreglo**"""

precios = np.array([24000, 28000, 22000, 30000, 8000])

print(type(precios).__name__)
print(precios.dtype)

"""# **3 Los tres atributos Básico**
Averigüe la forma, el número de dimensiones y la cantidad de elementos.
"""

matriz = np.array([[2, 24000],
                  [1, 28000],
                  [3, 22000]])

print(f"la forma de la matriz es: {matriz.shape}") # forma
print(f"la dimensión de la matriz es: {matriz.ndim}") # dimensiones
print(f"El t de la matriz es: {matriz.size}") # total de elementos
print(matriz.dtype)

"""# **4 Secuencias automáticas Básico**
Genere una secuencia con paso fijo, otra con extremos fijos y un arreglo de ceros.
"""

secuencia = np.arange(0, 10, 2)
rango = np.linspace(0, 1, 5)
ceros = np.zeros(5)

print(secuencia)
print(rango)
print(ceros.dtype)

"""# **5 Corrección: falta algo Intermedio**
Este bloque lanza TypeError: array() takes from 1 to 2 positional arguments but 3 were given
"""

# precios=np.,array(24000, 28000, 22000) faltan los []
precios=np.array([24000, 28000, 22000])

print(precios)

"""# **B Vectorización y broadcasting**
Operar sobre el arreglo completo, sin escribir un solo ciclo.

# **6 Multiplicar dos arreglos Básico**
Calcule el ingreso de cada transacción multiplicando elemento por elemento.
"""

cantidades=np.array([2, 1, 3, 2, 1])
precios=np.array([24000, 28000, 22000, 30000, 8000])

ingresos=cantidades*precios
total=ingresos.sum()
print(ingresos)
print(f"El total de ingresos es: {total}")

"""# **7 El escalar se estira Básico**
Aplique un descuento del diez por ciento a todos los precios.
"""

con_descuento=precios*0.9
print(con_descuento)
print(con_descuento.dtype)

"""# **8 El mismo cálculo, dos formas Intermedio**
Escriba con NumPy lo que el ciclo hace con listas
"""

# con listas python
lista = [24000, 28000, 22000, 30000, 8000]
resultado=[]

for p in lista:
  resultado.append(p*1.19)

print(resultado)

# con NumPy, en una sola línea

resultado_np = np.array(lista)*1.19
print(resultado_np)

"""# **9 Predicción: lista o arreglo Intermedio**
El mismo operador sobre dos estructuras distintas.
Escriba las dos salidas antes de ejecutar. Después explique qué hace la multiplicación sobre una lista y
qué hace sobre un arreglo.
"""

lista=[1,2,3]
arreglo=np.array([1,2,3])

print(lista*2) # este lo que hace es duplicar o triplicar la lista dependiendo el operador que se le ponga despues del *.
print(arreglo*2) # Este multiplica todos los valores de la lista por el operadores que va despues del *.

"""# **10 Predicción: formas distintas Intermedio**
Un arreglo de cinco elementos multiplicado por uno de cuatro.
¿Devuelve un resultado o lanza un error? Escriba su predicción, ejecute y anote el nombre del error si lo
hay
"""

a=np.array([2,1,3,2,1])
b=np.array([10,20,30,40])

print(a*b) # Arroja error porque las dos listas no tienen la misma longitud en este caso habria que incluir un nuevo valor a la lista mas corta o retirar uno del que tiene mas

"""# **11 Corrección: el ciclo sobra Intermedio**
El bloque funciona, pero desaprovecha NumPy por completo.
Reescríbalo en una sola línea vectorizada y explique qué se gana además de escribir menos
"""

ingresos=np.zeros(5)
for i in range(5):
  ingresos[i]=cantidades[i]*precios[i]

ingresos = precios*cantidades # se gana logica para quien este viendo el codigo
ingresos

"""# **C Indexación, rebanado y máscaras**
Seleccionar por posición y, sobre todo, seleccionar por condición.

# **12 Primero, último y una porción Básico**
Obtenga elementos por posición sin contar cuántos hay.
"""

print(precios[0]) # el primero
print(precios[-1]) # el último
print(precios[1:4]) # las posiciones 1, 2 y 3

"""# **13 La máscara booleana Intermedio**
Construya la condición y úsela para filtrar.
"""

mascara=precios>20000

print(mascara)
print(precios[mascara])
print(precios[mascara].sum())

"""# **14 Dos condiciones a la vez Intermedio**
Precios mayores a 10.000 y menores a 29.000. Recuerde el operador correcto.
"""

seleccion=precios[(precios>10000)&(precios<29000)]

print(seleccion)

"""# **15 Etiquetar según una condición Intermedio**
Clasifique cada precio sin escribir un ciclo ni un if.
"""

etiquetas = np.where(precios > 25000, "alto", "normal")
print(etiquetas)

"""# **16 Contar y sumar lo filtrado Básico**
Cuántos elementos cumplen la condición y cuánto suman.
"""

caros = precios[precios > 20000]
print(caros.size) # cuántos son
print(caros.sum()) # cuánto suman

"""# ***17 Corrección: el operador equivocado Avanzado***
Este bloque lanza ValueError: The truth value of an array with more than one element is
ambiguous.

"""

#seleccion = precios[(precios > 10000) and (precios < 29000)] Esta mal porque en NumPy el Y es con "&"
seleccion = precios[(precios > 10000) & (precios < 29000)]
print(seleccion)

"""# **D Agregar y resumir**
Reducir muchos valores a uno, sobre todo el arreglo o a lo largo de un eje.

# **18 Las funciones de resumen Básico**
Complete cada línea con el método que corresponde
"""

ingresos=np.array([48000, 28000, 66000, 60000, 8000])

print(ingresos.sum()) # 210000
print(ingresos.mean()) # 42000.0
print(ingresos.max()) # 66000
print(round(ingresos.std(), 2))

"""# **19 Sumar por columna Intermedio**
Cada fila es un producto y cada columna una sede. Obtenga el total de cada sede.
"""

matriz = np.array([[48000, 28000],
 [66000, 60000],
 [ 8000, 12000]])

print(matriz.sum(axis=0))

"""# **20 Sumar por fila y en total Intermedio**
Ahora el total de cada producto y el total general.
"""

print(matriz.sum(axis=1))
print(matriz.sum())

"""# **21 Predicción: el eje que confunde Avanzado**
Sin ejecutar nada todavía, escriba su predicción y después compruébela.
"""

print(matriz.mean(axis=0)) # Es el promedio de las columnas de la matriz cada valor es de cada columna

"""# **E Del arreglo a la tabla**
El arreglo resuelve el cálculo; el DataFrame le pone nombre a las columnas.

# **22 Crear e inspeccionar el DataFrame Básico**
Convierta la lista de diccionarios del caso en una tabla y revise su estructura.
"""

# diccionario para convertir en data frame
datos_ventas= {"fecha": ["3/08/2026", "3/08/2026", "4/08/2026"],
                        "Cliente ID": [101,102,103],
                        "Producto": ["Bowl Andino","Pasta Urbana","Bowl Andino"],
                        "Categoría": ["Almuerzo","Almuerzo","Almuerzo"],
                        "Cantidad": [2, 1, 1],
                        "Precio Unitario": [24000.00, 28000.00, 24000.00],
                        "Costo Unitario": [14000.00, 17000.00, 14000.00],
                        "Sede": ["Centro","NORTE","Centro"]
            }

print(datos_ventas)

import pandas as pd
df_ventas = pd.DataFrame(datos_ventas)
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"])
print(df_ventas.shape) # forma de la tabla
df_ventas.head(3) # primeras tres filas

"""# **23 Una columna o varias Básico**
Complete los corchetes para obtener primero una Series y después un DataFrame.
"""

una = df_ventas["Producto"]
varias = df_ventas[["Producto","Cantidad"]]

print(type(una).__name__, type(varias).__name__)

"""# **24 Predicción: qué hay debajo de una columna Intermedio**
pandas está construido sobre NumPy. Compruébelo
Escriba qué tipo de objeto cree que devuelve to_numpy() y cuánto suman las cantidades. Después
ejecute y compare.
"""

arreglo = df_ventas["Cantidad"].to_numpy()

print(type(arreglo).__name__)
print(arreglo.sum())
 # vuelve la variable Cantidad un arreglo de NumPy y cuando se suma da 4

"""# **25 Predicción: el rango que no se comporta igual Avanzado**
Dos formas de localizar filas, dos resultados distintos.
¿Cuántas filas devuelve cada línea? Escriba su predicción, ejecute y explique la diferencia en el manejo
del extremo final.
"""

print(df_ventas.loc[0:2].shape[0])
print(df_ventas.iloc[0:2].shape[0])

print(df_ventas.loc[0:1])
print(df_ventas.iloc[0:2])
# cada uno trae una fila loc por indice y iloc por posición sirve para filtrar

"""# **F Filtrar, derivar y agrupar**
La máscara booleana de NumPy, ahora sobre una tabla con nombres.

# **26 Filtrar con dos condiciones Intermedio**
Almuerzos de la sede Centro. Cada comparación va entre paréntesis
"""

mascara = (
 (df_ventas["Sede"] == "Centro")
 & (df_ventas["Categoría"] == "Almuerzo")
)
seleccion = df_ventas.loc[mascara].copy()
print(seleccion.shape[0], seleccion["Cantidad"].sum())

"""# **27 Columnas derivadas Básico**
Cree las tres columnas que permiten hablar de rentabilidad.
"""

df_ventas["ingreso"] = df_ventas["Cantidad"] * df_ventas["Precio Unitario"]
df_ventas["costo_total"] = df_ventas["Cantidad"] * df_ventas["Costo Unitario"]
df_ventas["margen_bruto"] = df_ventas["ingreso"] - df_ventas["costo_total"]
print(df_ventas["ingreso"].sum(), df_ventas["margen_bruto"].sum())

"""# **28 Indicadores globales Intermedio**
El porcentaje se calcula después de sumar, no antes.

"""

ingreso_total = df_ventas["ingreso"].sum()
margen_total = df_ventas["margen_bruto"].sum()
porcentaje_global = round(margen_total / ingreso_total * 100, 2)
ticket_promedio = round(ingreso_total / len(df_ventas), 2)
print(porcentaje_global, ticket_promedio)

"""# **29 Agrupar por producto Intermedio**
Construya la tabla de indicadores y observe el resultado antes de responder
La limonada tiene el mayor porcentaje de margen y el menor ingreso. ¿Qué decisión de negocio habilita
ese dato y cuál no?
"""

kpi = (
 df_ventas
 .groupby("Producto")
 .agg(
 ingreso=("ingreso", "sum"),
 margen=("margen_bruto", "sum"),
 )
 .reset_index()
)
kpi["porcentaje_margen"] = (kpi["margen"] / kpi["ingreso"] * 100).round(2)
print(kpi)

"""# **30 Reto integrador: el resumen ejecutivo Avanzado**
Encapsule el análisis en una función que reciba el DataFrame y no dependa de ninguna
variable global. Después aplíquela solo a la sede Centro.
"""

def resumen_ejecutivo(df):
    ingreso = df["ingreso"].sum()
    margen = df["margen_bruto"].sum()

    return {
        "total_ingresos": ingreso,
        "margen_bruto": margen,
        "porcentaje_margen": round(margen / ingreso * 100, 2),
        "ticket_promedio": round(ingreso / len(df), 2),
    }
print(resumen_ejecutivo(df_ventas))
solo_centro = df_ventas[df_ventas["Sede"] == "Centro"].copy()
print(resumen_ejecutivo(solo_centro))