# -*- coding: utf-8 -*-
"""EJERCICIOS DE PRACTICA FUNDAMENTOS PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15F__IGlJrdCyAe8e2YLxOgxNSlisR5nr

**# EJERCICIOS DE PRACTICA FUNDAMENTOS PYTHON**

Objetivo: Practicar la lectura contrucción y corrección de programas basicos que utilizan estructuras condicionales y repetitivas

# **A. De la lógica a la decisión**

Condiciones simples y estructuras if / else

**# 1 Completa una decisión simple**:

Completa la condición para mostrar “Mayor de edad” cuando la variable edad sea mayor o
igual a 18.
"""

edad = 20
if edad >= 18:
  print("Mayor de edad")

"""**# 2 Agrega la ruta alternativa**

Completa la estructura para clasificar una temperatura como “Alta” si supera 30 grados y
“Normal” en caso contrario.
"""

temperatura = 32

if temperatura > 30:
  print("Alta")
elif temperatura <= 30:
  print("Normal")

"""# **3 Predice la salida**

Sin ejecutar, escribe exactamente qué imprimirá el programa
"""

numero = 7
if numero % 2 == 0:
 print("Par")
else:
 print("Impar")
# Predicción: valida si "numero" es par o impar dependiendo del numero asignado y su residuo "%".

"""# **B. Múltiples condiciones**

if / elif / else y orden de evaluación

# **4 Completa la clasificación**

Agrega las dos expresiones faltantes para clasificar la nota.
"""

nota = 4.5

if nota >= 4.5:
  print("Excelente")
elif nota >= 4.0:
  print("Muy buen desempeño")
elif nota >= 3.0:
  print("Aprobado")
else:
  print("No aprobado")

"""# 5 Corrige el orden

El programa pretende mostrar “Excelente” para notas de 4.5 o más. Reescribe únicamente el
bloque condicional en el orden correcto.

"""

# Planteamiento
nota = 4.8
if nota >= 3.0:
 print("Aprobado")
elif nota >= 4.5:
 print("Excelente")

# Solución
nota = 4.8
if nota >= 4.5:
  print("Excelente")
elif nota >= 3.0:
  print("Aprobado")

"""# **6 Traza la ejecución**

Escribe la salida para valor = 12. Después indica cuál condición fue la primera verdadera.

"""

valor = 12
if valor < 5:
 print("A")
elif valor < 10:
 print("B")
elif valor < 15:
 print("C")
else:
 print("D")

 # Rta: el valor C por que 12 es menor que 12 A Y B estarían por debajo

"""# **C. Operadores lógicos**

Construye condiciones con and, or y not

# **7 Acceso con dos requisitos**

Completa el operador lógico para permitir acceso solo cuando ambas variables sean
verdaderas
"""

usuario_activo = True
tiene_permiso = True

if usuario_activo and tiene_permiso:
  print("Acceso permitido")
else:
  print("Acceso denegado")

"""# **8 Dos rutas válidas**

Completa la condición: se permite continuar si existe correo válido o teléfono válido.
"""

correo_valido = False
telefono_valido = True

if correo_valido or telefono_valido:
  print("continuar registro")
else:
  print("Faltan datos de contacto")

# Quice probar con el AND
correo_valido = False
telefono_valido = True

if correo_valido and telefono_valido:
  print("continuar registro")
else:
  print("Faltan datos de contacto")

"""# **9 Usa negación**

Completa la condición usando not para mostrar el mensaje solo si la cuenta NO está
bloqueada
"""

cuenta_bloquea = False

if cuenta_bloquea is not True:
  print("Puede operar")

"""# **10 Recorre del 1 al 5**

Completa range() para imprimir los valores 1, 2, 3, 4 y 5.
"""

for numero in range(1,6):
  print(numero)

"""# **11 Recorre con paso**

Completa range() para imprimir 2, 4, 6, 8 y 10.

"""

for numero in range(2,11,2):
  print(numero)

# Caso especial sirve por ahi para cualquier cosita
for numero in (2,11):
  print(numero)

"""# **D. Estructura repetitiva for**
Recorrer rangos y controlar iteraciones

# **12 Predice el acumulado**

Sin ejecutar, determina el valor final de suma
"""

suma = 0
for i in range(1,4):
  suma = suma + i
print(suma)
# 0+1, 1+2, 3+3 = 6

"""# **E. Estructura repetitiva while**

Repetir mientras una condición permanezca verdadera

# **13 Completa el contador**

Completa la condición y la actualización para imprimir los números del 1 al 5.
"""

numero = 1

while numero <= 5:
  print(numero)
  numero=numero+1

# Mientras numero sea menor o igual que 5 entonces muestre la variable numero si abajo no se le suma a numero algo para que llegue a 5 el seguira imprimiendo numero en un ciclo infinito
numero = 1

while numero <= 5:
  print(numero)
  numero=numero+4

"""# **14 Encuentra el ciclo infinito**

El siguiente programa nunca termina. Corrige solo la línea que falta dentro del ciclo.
"""

numero = 1

while numero <= 5:
  print(numero)
  numero=numero+3 # esto lo frena

"""# **15 Control de intentos**

Completa el ciclo para permitir máximo 3 intentos. No modifiques las líneas ya escritas.
"""

intentos = 0

while intentos <= 2:
 clave = input("Ingrese la clave: ")
 intentos = intentos + 1

print("proceso finalizado")

"""# **F. Elegir y combinar estructuras**

for + if, while + condición y razonamiento sobre flujo

# **16 ¿for o while?**

Escribe la estructura que elegirías en cada situación.

Situación for / while
* Procesar exactamente 10 mediciones. ***for***
* Pedir una clave hasta que sea correcta. ***while***
* Imprimir los números del 1 al 20. ***for/while***
* Repetir un cálculo hasta que el error sea menor que 0.01. ***while***

# **17 Combina for + if**

Completa el programa para recorrer del 1 al 12 y mostrar únicamente los múltiplos de 3.
"""

for numero in range(1,13):
  if numero %3==0:
    print(numero)

"""# **18 Predice antes de ejecutar**

Escribe todas las líneas que producirá el programa.

"""

for numero in range(1,8):
  if numero < 3:
    print(numero, "A")
  elif numero < 6:
    print(numero, "B")
  else:
    print(numero, "C")

# 1 A, 2 A, 3 B, 4 B, 5 B, 6 C, 7 C

"""# **G. Del pseudocódigo a Python**

Conserva la lógica y cambia la representación

# **19 Traduce una decisión**

Completa el código Python para que represente exactamente el pseudocódigo mostrado.
"""

nota = float(input("Nota: "))

if nota >= 3.0:
  print("Aprobado")
else:
  print("No Aprobado")

"""# **20 Traduce una repetición**

Completa el programa Python equivalente al pseudocódigo.


"""

for i in range(1,5):
  print(i)

"""# **Reto integrador**

Combina entrada, repetición y decisión sin utilizar listas ni funciones

# **R Clasificación de temperaturas**

Completa todos los espacios. Antes de ejecutar, prueba mentalmente tu solución con los
valores: 15, 18, 22, 25 y 30.
"""

# Este es el mio de arepa :D
for t in range(15,30,3):
  t=float(input("Temperatura: "))

  if t < 18:
    print("Baja")
  elif t > 18 and t <=25:
    print("Normal")
  else:
    print("Alta")

# Este si es el correcto
for i in range(1,6):
  t=float(input("Temperatura: "))

  if t < 18:
    print("Baja")
  elif t > 18 and t <=25:
    print("Normal")
  else:
    print("Alta")

"""Autoevaluación rápida
1. ¿Puedo explicar cuándo usar if, elif y else?
  Rta: if si inicial, elif un si que sigue despues del inicial, else es el entonces
2. ¿Puedo distinguir cuándo conviene for y cuándo while?
  Rta: for Para un valor que este en haga algo. while: Mientras un valor cumpla algo haga algo.
3. ¿Puedo identificar el riesgo de un ciclo infinito?
  Rta: porque la condición se da para que nunca tenga limite.
4. ¿Puedo traducir una decisión o repetición desde pseudocódigo a Python?
  Rta: Si se puede analizando bien la propuesta
"""