# -*- coding: utf-8 -*-
"""Fundamentos de programación Python III.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPT3KYGCLicH0kd6bvNyTz5gqjFjP9_Y

Con  funcion
"""

def saludar(nombre):
  print("Hola", nombre)

saludar("Ana")

def doble(n):
  return n*2

salida = doble(4)
print(salida)

def suma(a, b=10):
  return a+b

x = suma(5)
y = suma(5, 2)
z = suma(b=1, a=1)

print(x, y, z)
# si yo no le doy valor siempre va a tomar de la funcion de abajo independiente lo que haya puesto arriba

"""# Ejercicio integrador
Cree una función que calcule el promedio de una lista de notas y otra que indique si ese promedio aprueba
"""

def promedio(notas):
  total = 0
  for n in notas:
    total=total+n
  return total/len(notas)

def aprueba(prom, minimo=3.0):
  return prom >= minimo

notas = (3.5, 4.2, 2.8)
prom = promedio(notas)

print("promedio:", prom)
if aprueba(prom):
  print("Aprobado")
else:
  print("No aprobado")

"""# **Ejercicios de práctica**

Fundamentos Python (3)
Funciones: definición, parámetros y return

# **1 Definir una función**

Complete la palabra clave que define una función.
"""

def saludar():
  print("hola")

saludar()

"""# **2 Llamar a la función BÁSICO**

Complete la línea que ejecuta la función ya definida.
"""

def bienvenida():
  print("Bienvenido al curso")

bienvenida()

"""# **3 Predice el orden de ejecución BÁSICO**

Sin ejecutar, determine en qué orden aparecen los mensajes.
"""

def uno():
  print("A")

print("B")
uno()
print("C")

# B, A, C

"""# **4 Corrige el orden BÁSICO**

El programa falla porque la función se llama antes de existir. Reescriba las líneas en el orden
correcto.
"""

'''
saludar("ana")

def saludar(nombre):
  print("Hola :", nombre)
'''
def saludar(nombre):
   print("Hola :", nombre)

saludar("Ana")

"""# **5 Función con un parámetro BÁSICO**

Complete el parámetro que recibe la función.
"""

def saludar(nombre):
 print("Hola,", nombre)

saludar("Ana")

"""**6 Reutilizar la misma función BÁSICO**

Llame tres veces a la misma función, cada vez con un precio distinto.
"""

def con_iva(precio):
  return precio*1.19

print(con_iva(10000))
print(con_iva(20000))
print(con_iva(500000))

"""# **B. Parámetros y argumentos**
Lo que la función recibe para trabajar

# **7 Función con dos parámetros BÁSICO**

Complete los dos parámetros que la función necesita.
"""

def area(base,altura):
  return base*altura

print(area(3, 4))
print(area(5, 12))

"""# **8 Completa la llamada BÁSICO**

Complete los argumentos para obtener exactamente el resultado indicado.
"""

def area(base,altura):
  return base*altura

print(area(5, 5))

"""# **9 Parámetro o argumento BÁSICO**

Observe la definición y la llamada, y distinga cada uno de los dos nombres.
"""

def doble(n):
  return n*2

resultado = doble(5)
print(resultado)
# n es el parametro
# 2 operador
# 5 es el argumento

"""# **10 Argumentos por posición BÁSICO**

Complete la llamada para que se imprima: Ana 20 Bogota
"""

def perfil(nombre, edad, ciudad):
  print(nombre, edad, ciudad)

perfil("Ana", 20, "Bogota")

"""# **11 Argumentos por nombre BÁSICO**

Complete los nombres de los parámetros para que el orden deje de importar.
"""

def perfil(nombre, edad, ciudad):
  print(nombre, edad, ciudad)

perfil(edad=20, nombre="Ana", ciudad="Bogota")

"""# **12 Valor por defecto BÁSICO**

Complete el valor por defecto del parámetro saludo.
"""

def saludar(nombre, saludo="Hola"):
  print(saludo, nombre)

saludar("Ana")

"""# **C. return y ámbito**

Lo que la función entrega y dónde vive cada dato

# **13 Devolver un valor BÁSICO**

Complete la palabra clave que entrega el resultado.
"""

def doble(n):
  return n*2

print(doble(5))

"""# **14 Usar el valor devuelto BÁSICO**

Complete la llamada para guardar el resultado y operar con él.
"""

def doble(n):
  return n*2

resultado=doble(6)
print(resultado)
print(resultado+1)

"""# **15 Función sin return BÁSICO**

Sin ejecutar, determine qué imprimen las dos últimas líneas.
"""

def saludo(nombre):
  print("Hola,", nombre)

x = saludo("Ana")
print(x)
# como la función no devuelve nada especificamente si no que imprime y print es solo imprimir. en este caso debería usarse return

def saludo(nombre):
  return "Hola,", nombre

x = saludo("Ana")
print(x)

"""# **16 print o return BÁSICO**

La suma falla porque la función no devuelve nada. Escriba la versión corregida de la función.

"""

'''
def doble(n):
  print(n*2)

total = doble(5)+3
'''

def doble(n):
  return n*2

total = doble(5)+3
print(total)

"""# **17 return dentro de una condición BÁSICO**

Complete la instrucción que devuelve el segundo resultado.

"""

def signo(n):
  if n<0:
    return "negativo"
  print("positivo")

print(signo(-4))
print(signo(7))

"""# **18 Función que recibe una lista INTERMEDIO**

Complete la función que calcula el promedio de una lista de notas.

"""

def promedio(notas):
  total=0
  for n in notas:
    notas = total+n
  return total/len(notas)

print(promedio([3.5, 4.2, 2.8]))

"""# **19 Variable local y global INTERMEDIO**

Sin ejecutar, determine qué imprime cada una de las dos últimas líneas.

"""

mensaje="global"

def prueba():
  mensaje="total"
  print(mensaje)

prueba()
print(mensaje)

# es porque el "mesnaje" que esta dentro de la función está desarrollado para la función y el de afuera es una variable distinta y una no afecta a la otra.

"""# **20 Reporte de notas con funciones INTERMEDIO**

Complete el programa que calcula el promedio de un estudiante y muestra si aprueba,
usando dos funciones
"""

def promedio(notas):
  total=0
  for n in notas:
    total = total+n
  return total/len(notas)

def reporte(nombre, notas):
  prom=promedio(notas)
  print(nombre,round(prom,2))
  if prom>=3.0:
    print("Aprobado")
  else:
    print("Aprobado")

reporte("Laura",[3.5, 4.2, 2.8])