# -*- coding: utf-8 -*-
"""PPT Fundamentos de programacion I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxSI-6kyh7bv8_oRTfQkZ6yK1Yn-mhJs

# **EJERCICIOS PPT FUNDAMENTOS DE PROGRAMACION I**

**SLIDE 4 Secuencia, selección y repetición**
"""

#SLIDE 4
precio = 100000
iva = precio * 0.19
total = precio+iva

print(precio)
print(iva)
print(total)

#SLIDE 4
if total > 100000:
  print("Compra de alto valor")
else:
  print("Compra de bajo valor")

#SLIDE 4
for i in range(5):
  print(i)

"""Slide 5
**De la proposición al if**
"""

edad = 20
if edad >= 18:
  print("Mayor de edad")

"""**SLIDE 6 ESTRUCTURAS CONDICIONALES**
if, elif y else
"""

nota = 3.8
if nota >= 3.0:
  print('Aprobó')
else:
  print('No aprobó')

"""**SLIDE 7 ORDEN DE LAS CONDICIONES IMPORTA**"""

# orden malo
nota = 4.7
if nota >= 3.0:
  print("Aprobadó")
elif nota >= 4.5:
  print("Excelente")

# orden correcto
nota = 4.7
if nota >= 4.5:
  print("Excelente")
elif nota >= 3.0:
  print("Aprobado")

"""**SLIDE 8 if elif y else**
evaluación de arriba hacia abajo
"""

nota = 4.2
if nota>=4.5:
  print("Excelente")
elif nota>=4.0:
  print("Muy buen desempeño")
elif nota>=3.0:
  print("Aprobado")
else:
  print("No Aprobado")

nota = 2.9
if nota>=4.5:
  print("Excelente")
elif nota>=4.0:
  print("Muy buen desempeño")
elif nota>=3.0:
  print("Aprobado")
else:
  print("No Aprobado")

"""**SLIDE 9 OPERADORES LOGICOS**"""

usuario_activo = True
tiene_permisos = True

if usuario_activo and tiene_permisos:
  print("Acceso permitido")
else:
  print("Acceso denegado")

"""**SLIDE 10 LA IDENTACION TAMBIEN ES SINTAXIS**"""

if nota >= 3.0:
  print("Aprobado")
else:
  print("No aprobado")

'''
Esta manera NO es incorrecta
if nota >= 3.0:
print("Aprobado")
else:
print("No aprobado")
'''

"""**SLIDE 11 ESTRUCTURAS REPETITIVAS:** for"""

for numero in range(1,6):
  print(numero)

"""**SLIDE 12 COMBINAR** for + if"""

for numero in range(1,11):
  if numero %2==0:
    print(numero,"es par")

"""**SLIDE 13 ESTRUCTURAS REPETITIVAS:** while"""

numero = 1

while numero <= 5:
  print(numero)
  numero = numero + 1

"""**SLIDE 14 WHILE APLICADO: no sabemos cuantos intentos habrá**"""

clave_correcta = "python123"
clave = ""

while clave!=clave_correcta:
  clave=input("ingrese contraseña")

print("acceso autorizado")

"""**SLIDE 15 for o while: ¿cual usar?**

for:

*   Cuando conozco cuantas veces repetir.
*   Cuando recorro rangos y secuencias.

while:

*   Cuando dependo de una condición.
*   Cuando no conozco el numero de iteraciones.


"""

#for:
for i in range(5):
  print(i)

# while:
numero=1
while numero <=5:
  print(numero)
  numero = numero + 1

"""**SLIDE 16 PREDIGA ANES DE APLICAR**"""

for numero in range(1,8):
  if numero < 3:
    print(numero, "A")
  elif numero < 6:
    print(numero, "B")
  else:
    print(numero,  "C")

for numero in range(-100,-90):
  print(numero)

"""SLIDE 17 EJERCICIO DE INTEGRADOR"""

#Ejercicio 2
for i in range(5):
  t = float(input('temperatura: '))

  if t < 18:
    print('temperatura baja')
  elif t < 25:
    print('temperatura normal')
  else:
    print('temperatura alta')

"""SLIDE 18 DEL SEUDO CODIGO A python"""

nota=float(input("Nota: "))

if nota > 3.0:
  print("Aprobado")
else:
  print("No aprobado")

nota=float(input("Nota: "))

if nota > 3.0:
  print("Aprobado")
else:
  print("No aprobado")